spring:
  application:
    name: Tarefator
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tarefator_db?useTimezone=true&serverTimezone=UTC
      username: root
      password: 3158
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true